{"uuid": "099b87cc-7bcc-4526-a6e7-057b7f742acd", "children": ["456224f0-9969-4ede-a608-f0b789476d8c"], "befores": [{"name": "registered_user", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/tests/conftest.py\", line 68, in registered_user\n    account_helper.register_new_user(login=login,password=password,email=email)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/helpers/account_helper.py\", line 58, in register_new_user\n    register_response = self.dm_account_api.account_api.post_v1_account(registration_initialized_object)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/dm_api_account/apis/account_api.py\", line 30, in post_v1_account\n    response = self.post(\n        path=f\"/v1/account\",\n        json= registration.model_dump(exclude_none=True, by_alias=True),\n        **kwargs\n    )\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/client.py\", line 27, in post\n    return self._send_request(method=\"POST\", path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/utilities.py\", line 16, in wrapper\n    response = fn(*args, **kwargs)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/client.py\", line 64, in _send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "register new user", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/helpers/account_helper.py\", line 58, in register_new_user\n    register_response = self.dm_account_api.account_api.post_v1_account(registration_initialized_object)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/dm_api_account/apis/account_api.py\", line 30, in post_v1_account\n    response = self.post(\n        path=f\"/v1/account\",\n        json= registration.model_dump(exclude_none=True, by_alias=True),\n        **kwargs\n    )\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/client.py\", line 27, in post\n    return self._send_request(method=\"POST\", path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/utilities.py\", line 16, in wrapper\n    response = fn(*args, **kwargs)\n  File \"/Users/sergeygureev/PycharmProjects/my_api_tests/restclient/client.py\", line 64, in _send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "attachments": [{"name": "request_body", "source": "998f870f-c425-41fc-9727-75a0419d7064-attachment.json", "type": "application/json"}], "parameters": [{"name": "login", "value": "'sgureev+1749307891'"}, {"name": "email", "value": "'sgureev+1749307891@mail.ru'"}, {"name": "password", "value": "'123456789'"}], "start": 1749307891646, "stop": 1749307891959}], "start": 1749307891646, "stop": 1749307891963}], "start": 1749307891646, "stop": 1749307892005}